# Generated by Django 4.1.2 on 2025-05-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
